from PIL import Image, ImageDraw, ImageFont, ImageFilter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "examples" / "ESP32C3_All_BLE_Tester"
SRC = Path(__file__).resolve().parent / "chromium_logo_history_source.jpg"
JPG = OUT / "dino.jpg"
HDR = OUT / "dino_jpg.h"

# Keep the BLE transfer demo reasonably sized while retaining enough detail for
# visible progressive refinement. 640px wide gives a good balance for the ESP32-C3
# and Web Bluetooth chunking.
W, H = 640, 568

src = Image.open(SRC).convert("RGB")
# Fit the full logo-history image into the canvas without cropping.
src.thumbnail((W, H), Image.Resampling.LANCZOS)
img = Image.new("RGB", (W, H), (18, 18, 18))
x = (W - src.width) // 2
y = (H - src.height) // 2
img.paste(src, (x, y))

# Add a subtle dark frame and sharp high-frequency details around the source image.
# These make progressive scans very obvious: first a blurry full-frame preview,
# then the logo text/edges and chunk marks become crisp.
d = ImageDraw.Draw(img)
for gx in range(0, W, 32):
    d.line([(gx, 0), (gx, H)], fill=(235, 235, 235), width=1)
for gy in range(0, H, 32):
    d.line([(0, gy), (W, gy)], fill=(40, 40, 40), width=1)
# Re-paste the actual requested image on top so the demo details do not cover it.
img.paste(src, (x, y))
d = ImageDraw.Draw(img)

def font(size, bold=False):
    candidates = [
        "C:/Windows/Fonts/consolab.ttf" if bold else "C:/Windows/Fonts/consola.ttf",
        "C:/Windows/Fonts/arialbd.ttf" if bold else "C:/Windows/Fonts/arial.ttf",
    ]
    for candidate in candidates:
        try:
            return ImageFont.truetype(candidate, size)
        except Exception:
            pass
    return ImageFont.load_default()

f_small = font(14, False)
f_num = font(15, True)

# Bottom strip outside the main image. It demonstrates fine detail sharpening
# without altering the requested Chromium logo-history artwork.
panel_h = 44
d.rounded_rectangle((14, H - panel_h - 10, W - 14, H - 8), radius=10,
                    fill=(0, 0, 0), outline=(255, 193, 7), width=2)
d.text((28, H - panel_h - 2), "BLE progressive JPEG: blurry preview first, then Chromium logo/history text sharpens chunk by chunk",
       font=f_small, fill=(255, 255, 255))
for i in range(18):
    x0 = 30 + i * 32
    y0 = H - 26
    color = (255, 193, 7) if i % 2 == 0 else (106, 191, 105)
    d.rectangle((x0, y0, x0 + 22, y0 + 16), fill=color, outline=(0, 0, 0), width=1)
    d.text((x0 + 4, y0 - 1), str(i % 10), font=f_num, fill=(0, 0, 0))

img = img.filter(ImageFilter.UnsharpMask(radius=0.8, percent=110, threshold=2))

# Important: progressive=True. Quality 58 intentionally keeps the file small and
# makes the successive progressive scans easy to see over BLE.
img.save(JPG, "JPEG", quality=58, optimize=True, progressive=True)

data = JPG.read_bytes()
lines = [
    "#pragma once",
    "#include <Arduino.h>",
    "",
    "// Generated by tools/make_progressive_demo_image.py",
    "// Source: https://logos-world.net/wp-content/uploads/2025/07/Chromium-Logo-History.jpg",
    "// Progressive JPEG demo image for BLE chunked transfer.",
    f"static const uint32_t DINO_JPG_LEN = {len(data)};",
    "static const uint8_t DINO_JPG[] PROGMEM = {",
]
for i in range(0, len(data), 12):
    chunk = data[i:i + 12]
    suffix = "," if i + 12 < len(data) else ""
    lines.append("  " + ", ".join(f"0x{b:02X}" for b in chunk) + suffix)
lines.append("};")
HDR.write_text("\n".join(lines) + "\n", encoding="ascii")

print(f"wrote {JPG} ({len(data)} bytes)")
print(f"wrote {HDR}")
